# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dickpic',
            name='pic',
            field=models.ImageField(upload_to='dicks'),
        ),
    ]
